### ISSUE TITLE
Web page very slow to load

### ISSUE THREAD

**Issue by Blistex77** [trinib/AdGuard-WireGuard-Unbound-Cloudflare#13]
Hi,

I had followed the previous guide without Stubby on a Raspberry Pi and it was great. This time, I'm using an new with the new set up and I notice that it takes a very long time to load web pages. If I add another server (9.9.9.9 for instance) to the upstream DNS, then everything is fine.

The average process time is less than 10ms though, so I'm not sure which part is guilty of the slowness. Could Unbound/Stubby cause the issue?

Could you give me any hint towards troubleshooting this?

Thanks!

**Comment by trinib** [comment]
what latency you get with your isp default dns ?.. i get almost same latency as my isp dns with my setup around 5ms to 10ms .. but you said you use quad9 and get not latency .. but do you get `doh` and`dot` saying yes on android device.. dont test on windows for now cause it gets a hit and miss but i have a fix that i will upload soon :)..

**Comment by trinib** [comment]
try using 
127.0.0.1:53
or
127.0.0.1:5053
or
127.0.0.1:8053
one by one and see

**Comment by Blistex77** [comment]
Well it does work for me as well, it's just that when I apply the exact same set up as the guilde
- web pages (no matter the browser) are longer to load
- Adguard's average processing time is > 10ms so it's not a processing latency issue

I'm trying each option after the other and will let you know how it goes.

Thanks for the help!

**Comment by trinib** [comment]
all pages load fine for me ..you will have to recheck your settings

**Comment by trinib** [comment]
Hello ... did you resolve issue ?
