### ISSUE TITLE
Auto update for pi

### ISSUE THREAD

**Issue by VuzzyM** [trinib/AdGuard-WireGuard-Unbound-Cloudflare#21]
### Operating System

64-bit

### Project

Aduard Home

### Platform

Linux

### Browser

Other

### Issue

Other (explain in description)

### Issue Description

Hello 

Config crontab for auto update pi is work on ubuntu?

Thanks for answer.

**Comment by trinib** [comment]
Update script should work just like in Raspbian OS(Debian) ..  Ubuntu is a branch of Debain btw, here is a [GNU tree](https://5thlobe.com/wp-content/uploads/2016/03/GNU_Linux-distro-timeline_S.svg) history

**Comment by trinib** [comment]
@VuzzyM if you want check out [unattended upgrade](https://www.faqforge.com/linux/how-to-enable-auto-updates-in-ubuntu/)
