### ISSUE TITLE
DNS over TLS not working

### ISSUE THREAD

**Issue by karim1104** [trinib/AdGuard-WireGuard-Unbound-Cloudflare#23]
Hi,

DoT doesn't work. Please see my [1.1.1.1/help report](https://1.1.1.1/help#eyJpc0NmIjoiWWVzIiwiaXNEb3QiOiJObyIsImlzRG9oIjoiWWVzIiwicmVzb2x2ZXJJcC0xLjEuMS4xIjoiWWVzIiwicmVzb2x2ZXJJcC0xLjAuMC4xIjoiWWVzIiwicmVzb2x2ZXJJcC0yNjA2OjQ3MDA6NDcwMDo6MTExMSI6Ik5vIiwicmVzb2x2ZXJJcC0yNjA2OjQ3MDA6NDcwMDo6MTAwMSI6Ik5vIiwiZGF0YWNlbnRlckxvY2F0aW9uIjoiRFhCIiwiaXNXYXJwIjoiTm8iLCJpc3BOYW1lIjoiQ2xvdWRmbGFyZSIsImlzcEFzbiI6IjEzMzM1In0=). 
I installed AdGuard-Unbound-Cloudflare on a public domain and installed Let's Encrypt SSL certificate. Do you think that's affecting it?

**Comment by trinib** [comment]
not sure

**Comment by trinib** [comment]
Did you check your DoT is actually working ?
