### ISSUE TITLE
[feature]: Leverage Black Mirror to handle general blacklisting

### ISSUE THREAD

**Issue by T145** [trinib/AdGuard-WireGuard-Unbound-Cloudflare#25]
https://github.com/T145/black-mirror

Any non-deprecated sources used here can be added into Black Mirror. The `exports` directory holds raw source lists.

**Comment by trinib** [comment]
@T145 Sweet !! ..  I doubt your missing what i have lol.. can still check and send PR , need to redirect this in README😎. Will set you as collaborator, nice work👊

**Comment by T145** [comment]
After reviewing the sources you've used I'm confident in saying that its content is contained w/in Black Mirror. Therefore we can replace it entirely.

**Comment by trinib** [comment]
> After reviewing the sources you've used I'm confident in saying that its content is contained w/in Black Mirror. Therefore we can replace it entirely.

yes i removed my list of sources . I'll remove my blocklist as well for i cant keep track of it like you do
