### ISSUE TITLE
wget: unable to resolve host address ‘bin.equinox.io’

### ISSUE THREAD

**Issue by CommittotheIndian** [trinib/AdGuard-WireGuard-Unbound-Cloudflare#3]
I have been trying all day to download and extract Cloudflare:
`wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.tgz && tar -xvzf cloudflared-stable-linux-arm.tgz`

I keep getting `wget: unable to resolve host address ‘bin.equinox.io’`
I've tried changing the namerserver, I've refreshed and started over. Nothing seems to work. I can't find a solution.

**Comment by trinib** [comment]
> I have been trying all day to download and extract Cloudflare:
> `wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.tgz && tar -xvzf cloudflared-stable-linux-arm.tgz`
> 
> 
> I keep getting `wget: unable to resolve host address ‘bin.equinox.io’`
> I've tried changing the namerserver, I've refreshed and started over. Nothing seems to work. I can't find a solution.

link is currently working for me.. it looks like a internet connection issue with you.. try

     ping google.com

and see if you have a proper connection

**Comment by CommittotheIndian** [comment]
Pinging google.com does not work work but 8.8.8.8 works.

**Comment by trinib** [comment]
> Pinging google.com does not work work but 8.8.8.8 works. 

well something is wrong with connection to internet on device, what os and hardware are you using?

**Comment by CommittotheIndian** [comment]
`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian`

I think this is on a Rpi 3b+. I'm trying to setup this SD before transferring it to my pi-hole raspberry (Rpi 4b+) running my current DNS.

**Comment by trinib** [comment]
> `PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian`
> 
> I think this is on a Rpi 3b+. I'm trying to setup this SD before transferring it to my pi-hole raspberry (Rpi 4b+) running my current DNS.

ohh so if fresh install os image and do a ping test do you get same issue.. is it ethernet cable or wifi?.

**Comment by CommittotheIndian** [comment]
I've done 1 fresh install. I'd have to try again. It is ethernet cable.

**Comment by trinib** [comment]
> `PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian`
> 
> I think this is on a Rpi 3b+. I'm trying to setup this SD before transferring it to my pi-hole raspberry (Rpi 4b+) running my current DNS.

and  I don't think you can switch SD card between pi 3 and 4 cause of os image for that specific hardware

**Comment by trinib** [comment]
> I've done 1 fresh install. I'd have to try again. It is ethernet cable.
> 

OK do that and ping test and install cloudflare first and if working something you did before messed up connection

**Comment by trinib** [comment]
> I've done 1 fresh install. I'd have to try again. It is ethernet cable.
> 

@CommittotheIndian  did everything work out fine?

**Comment by CommittotheIndian** [comment]
I'm still working on it. I was able to get cloudflare to load when I did that step first but then I started getting errors on AdGuard.

**Comment by CommittotheIndian** [comment]
You've closed this issue prematurely (didn't even give me time to respond). 

When I load AdGuard first, Cloudflare won't load. 

When I load Cloudflare first, AdGuard throws errors.
`Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *fmt.wrapError updater: HTTP GET https://static.adguard.com/adguardhome/release/version.json: Get "https://static.adguard.com/adguardhome/release/version.json": couldn't initialize HTTP client or transport, cause: timeout exceeded: 10001 ms | 502`

Your process is flawed.

**Comment by trinib** [comment]
> You've closed this issue prematurely (didn't even give me time to respond). 
> 
> When I load AdGuard first, Cloudflare won't load. 
> 
> When I load Cloudflare first, AdGuard throws errors.
> `Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *fmt.wrapError updater: HTTP GET https://static.adguard.com/adguardhome/release/version.json: Get "https://static.adguard.com/adguardhome/release/version.json": couldn't initialize HTTP client or transport, cause: timeout exceeded: 10001 ms | 502`
> 
> Your process is flawed.

you need to make pi ip address static.. I closed issue cause its not a issue when it's working.

**Comment by trinib** [comment]
> You've closed this issue prematurely (didn't even give me time to respond). 
> 
> When I load AdGuard first, Cloudflare won't load. 
> 
> When I load Cloudflare first, AdGuard throws errors.
> `Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *fmt.wrapError updater: HTTP GET https://static.adguard.com/adguardhome/release/version.json: Get "https://static.adguard.com/adguardhome/release/version.json": couldn't initialize HTTP client or transport, cause: timeout exceeded: 10001 ms | 502`
> 
> Your process is flawed.

and procees is not flawed.. you need to follow instructions

**Comment by CommittotheIndian** [comment]
The IP is static. The process of your steps is not working. Your GitHub isn't for software, its for the process of installing and launching software. That process is flawed.

If I do AdGuard first, I can't get cloud flare. If I get Cloudflare first, I can't get AdGuard (at least not your links) and can't get Unbound.

I've been working on this all day, multiple  variations, erasing and re-flashing. Nothing is working.

**Comment by CommittotheIndian** [comment]
> > You've closed this issue prematurely (didn't even give me time to respond).
> > When I load AdGuard first, Cloudflare won't load.
> > When I load Cloudflare first, AdGuard throws errors.
> > `Error: control/version.json | Couldn't get version check json from https://static.adguard.com/adguardhome/release/version.json: *fmt.wrapError updater: HTTP GET https://static.adguard.com/adguardhome/release/version.json: Get "https://static.adguard.com/adguardhome/release/version.json": couldn't initialize HTTP client or transport, cause: timeout exceeded: 10001 ms | 502`
> > Your process is flawed.
> 
> and procees is not flawed.. you need to follow instructions

Explain what instruction you think I'm missing. I'll be glad to prove you wrong when it still doesn't work.

**Comment by CommittotheIndian** [comment]
If I follow your instructions I get `wget: unable to resolve host address ‘bin.equinox.io’` when I get to the Cloudflare DOH install.

I followed your next suggestion and did Cloudflare. Then I go back to your instructions and get `wget -O root.hints https://www.internic.net/domain/named.root && sudo mv root.hints /var/lib/unbound/
--2021-06-28 23:02:36--  https://www.internic.net/domain/named.root
Resolving www.internic.net (www.internic.net)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘www.internic.net’`

So no matter which path I take, something isn't communicating correctly.

**Comment by trinib** [comment]
> The IP is static. The process of your steps is not working. Your GitHub isn't for software, its for the process of installing and launching software. That process is flawed.
> 
> If I do AdGuard first, I can't get cloud flare. If I get Cloudflare first, I can't get AdGuard (at least not your links) and can't get Unbound.
> 
> I've been working on this all day, multiple  variations, erasing and re-flashing. Nothing is working.
> 

cuase when you install adguard first you need

and do not install cloudflare first.. I think it's that adguard issue.. so let me know

**Comment by CommittotheIndian** [comment]
> > I've done 1 fresh install. I'd have to try again. It is ethernet cable.
> 
> OK do that and ping test and install cloudflare first and if working something you did before messed up connection

You told me to try Cloudflare first.

If I do AdGuard first, I can't install Cloudflare. If I do Cloudflare first, I can't install anything else.

Using other links, I was able to get all installed but the test links revealed I wasn't ever using Cloudflare DOH or DOT.

**Comment by trinib** [comment]
> If I follow your instructions I get `wget: unable to resolve host address ‘bin.equinox.io’` when I get to the Cloudflare DOH install.
> 
> I followed your next suggestion and did Cloudflare. Then I go back to your instructions and get `wget -O root.hints https://www.internic.net/domain/named.root && sudo mv root.hints /var/lib/unbound/
> --2021-06-28 23:02:36--  https://www.internic.net/domain/named.root
> Resolving www.internic.net (www.internic.net)... failed: Temporary failure in name resolution.
> wget: unable to resolve host address ‘www.internic.net’`
> 
> So no matter which path I take, something isn't communicating correctly.

so sudo apt install unbound -y working and then `wget -O root.hints https://www.internic.net/domain/named.root && sudo mv root.hints /var/lib/unbound/' does not?

**Comment by CommittotheIndian** [comment]
> > If I follow your instructions I get `wget: unable to resolve host address ‘bin.equinox.io’` when I get to the Cloudflare DOH install.
> > I followed your next suggestion and did Cloudflare. Then I go back to your instructions and get `wget -O root.hints https://www.internic.net/domain/named.root && sudo mv root.hints /var/lib/unbound/ --2021-06-28 23:02:36--  https://www.internic.net/domain/named.root Resolving www.internic.net (www.internic.net)... failed: Temporary failure in name resolution. wget: unable to resolve host address ‘www.internic.net’`
> > So no matter which path I take, something isn't communicating correctly.
> 
> so sudo apt install unbound -y working and then `wget -O root.hints https://www.internic.net/domain/named.root && sudo mv root.hints /var/lib/unbound/' does not?

correct

**Comment by trinib** [comment]
> > > If I follow your instructions I get `wget: unable to resolve host address ‘bin.equinox.io’` when I get to the Cloudflare DOH install.
> > > I followed your next suggestion and did Cloudflare. Then I go back to your instructions and get `wget -O root.hints https://www.internic.net/domain/named.root && sudo mv root.hints /var/lib/unbound/ --2021-06-28 23:02:36--  https://www.internic.net/domain/named.root Resolving www.internic.net (www.internic.net)... failed: Temporary failure in name resolution. wget: unable to resolve host address ‘www.internic.net’`
> > > So no matter which path I take, something isn't communicating correctly.
> > 
> > so sudo apt install unbound -y working and then `wget -O root.hints https://www.internic.net/domain/named.root && sudo mv root.hints /var/lib/unbound/' does not?
> 
> correct

so is wget working with other links?

**Comment by trinib** [comment]
go to adguard home page, select "step guide" and take a screenshot let me seen something

**Comment by CommittotheIndian** [comment]
<img width="947" alt="Screen Shot 2021-06-28 at 6 29 51 PM" src="https://user-images.githubusercontent.com/60204668/123711706-e8308d00-d83e-11eb-8232-89a9e8e36534.png">


I've also started getting this error in AdGuard
<img width="959" alt="Screen Shot 2021-06-28 at 6 33 22 PM" src="https://user-images.githubusercontent.com/60204668/123711978-60974e00-d83f-11eb-9c53-6cf8eb8bbf52.png">

**Comment by CommittotheIndian** [comment]
Once I get AdGuard (even though my network is still pointed at 1.1.1.1 and not the AdGuard) the RPi I'm running it on, can not get to anything else. Here I'm tryin api update & apt upgrade again.

`Err:1 http://archive.raspberrypi.org/debian buster InRelease                       
  Temporary failure resolving 'archive.raspberrypi.org'
Err:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                    
  Temporary failure resolving 'raspbian.raspberrypi.org'
Reading package lists... Done              
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease  Temporary failure resolving 'raspbian.raspberrypi.org'
W: Failed to fetch http://archive.raspberrypi.org/debian/dists/buster/InRelease  Temporary failure resolving 'archive.raspberrypi.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  python-colorzero
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by CommittotheIndian** [comment]
I just tried a new SD card and new RPi 4+. With AdGuard installed, I can't even install sudo apt-update/upgrade packages.

`Err:1 http://raspbian.raspberrypi.org/raspbian buster InRelease                    
  Temporary failure resolving 'raspbian.raspberrypi.org'`

**Comment by trinib** [comment]
> I just tried a new SD card and new RPi 4+. With AdGuard installed, I can't even install sudo apt-update/upgrade packages.
> 
> `Err:1 http://raspbian.raspberrypi.org/raspbian buster InRelease                    
>   Temporary failure resolving 'raspbian.raspberrypi.org'`
> 
> `Err:1 http://raspbian.raspberrypi.org/raspbian buster/main armhf dns-root-data all 2019031302
>   Temporary failure resolving 'raspbian.raspberrypi.org'
> `

> is your port 50 and 53 open?.. is there a firewall on your router?..

**Comment by CommittotheIndian** [comment]
I have a Unifi system. 

My 2nd firewall rules allow all traffic to my DNS server (currently my Pi-hole) and port 53. 

3rd rule allows all DNS traffic allows my DNS Server to port 53. 

I don’t believe I have any specific rules for port 50 right now.

**Comment by trinib** [comment]
> 
> 
> I have a Unifi system.
> 
> My 2nd firewall rules allow all traffic to my DNS server (currently my Pi-hole) and port 53.
> 
> 3rd rule allows all DNS traffic allows my DNS Server to port 53.
> 
> I don’t believe I have any specific rules for port 50 right now.

so your raspberry pi is connected to pihole when you are installing adguard?

**Comment by CommittotheIndian** [comment]
I thought about that. I’ve tried it with disabling pi-hole. I’ve tried changing my DNS service to cloudflare or Google (bypassing pi-hole) and even tried installing on a blank SD in the pi-hole rpi, so no actual pi-hole instance. 

Nothing worked. As soon as AdGuard is installed, I start getting blocked (even with it disabled and no traffic directed at it).

**Comment by trinib** [comment]
> I thought about that. I’ve tried it with disabling pi-hole. I’ve tried changing my DNS service to cloudflare or Google (bypassing pi-hole) and even tried installing on a blank SD in the pi-hole rpi, so no actual pi-hole instance. 
> 
> Nothing worked. As soon as AdGuard is installed, I start getting blocked (even with it disabled and no traffic directed at it). 

you should just use isp provider default dns

**Comment by CommittotheIndian** [comment]
Ok. I had to go out of town for a couple days. I’ll give that a try when I get home or attempt to try this setup on a different internet connection.

**Comment by trinib** [comment]
> Ok. I had to go out of town for a couple days. I’ll give that a try when I get home or attempt to try this setup on a different internet connection. 

yes it has to be some setting on router or some other dns service causing conflict with port 53 or 50.. that's the only thing I can think of

**Comment by CommittotheIndian** [comment]
Ok, I think I resolved all my issues.

After installing AdGuard, I had to change the name server DNS `sudo nano /etc/resolv.conf`. I changed it to my ISP provided DNS which allowed me to install all other packages and set them up without issue. Later reboots, changes it back to `127.0.0.1`.

I have noticed sometimes DNS over TLS is yes and other times it is no, usually a refresh changes it one way or the other. I assume that has to do with the setting of the fastest IP address.

![IMG_5474](https://user-images.githubusercontent.com/60204668/124394420-6b356580-dccd-11eb-96e7-1ebbaff6dba2.PNG)
![IMG_5475](https://user-images.githubusercontent.com/60204668/124394421-6d97bf80-dccd-11eb-8fbe-b1c14fc1489a.PNG)


Other than figuring out the allow (white) lists, everything seems to be running.

**Comment by trinib** [comment]
> Ok, I think I resolved all my issues.
> 
> After installing AdGuard, I had to change the name server DNS `sudo nano /etc/resolv.conf`. I changed it to my ISP provided DNS which allowed me to install all other packages and set them up without issue. Later reboots, changes it back to `127.0.0.1`.
> 
> I have noticed sometimes DNS over TLS is yes and other times it is no, usually a refresh changes it one way or the other. I assume that has to do with the setting of the fastest IP address.
> 
> ![IMG_5474](https://user-images.githubusercontent.com/60204668/124394420-6b356580-dccd-11eb-96e7-1ebbaff6dba2.PNG)
> ![IMG_5475](https://user-images.githubusercontent.com/60204668/124394421-6d97bf80-dccd-11eb-8fbe-b1c14fc1489a.PNG)
> 
> 
> Other than figuring out the allow (white) lists, everything seems to be running.

good news 👍

what bowser you using and what device?.. try to fix the hit and miss with DoT

**Comment by CommittotheIndian** [comment]
I used Safari on a MacBook Air. I’ll try a different browser later, didn’t think about it.
