### ISSUE TITLE
How to: Make AdGuard UI and DNS service ports only accessible via VPN

### ISSUE THREAD

**Issue by mp68** [trinib/AdGuard-WireGuard-Unbound-Cloudflare#42]
I was fiddling around a bit with ufw and decided to share my results with you: How to Make AdGuard UI and DNS service ports only accessible via VPN
Note: by enabling ufw you can block new connections required to manage your server (SSH). Make sure you keep an SSH connection to your server open and test the rules by opening a another SSH connection. Otherwise you risk loosing access to your server!

1.  Reset ufw to defaults
```
sudo ufw default deny incoming
sudo ufw default allow outgoing
```
2. Allow SSH access
```
sudo ufw allow ssh
``` 
3. Allow access to the Wireguard VPN server (in this case the default port used in this tutorial)
```
sudo ufw allow 51820
```
4. Identify network adapter used by Wireguard (can be identified by a name starting with "_wg_" followed by a number, if you start with a fresh install and follow this tutorial it should be _wg0_)
```
ip link show
```
5. Allow access to all ports by requests coming from the Wireguard network adapter
```
sudo ufw allow in on wg0
```
6. Enable ufw
```
sudo ufw enable
```
7. Check the status of ufw
```
sudo ufw status numbered
```

I hope you find these rules useful. Feedback, modifications and suggestions are welcome 😊

**Comment by trinib** [comment]
thanks👍. I already stated that in discussions https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare/discussions/14#discussioncomment-2707819 but forgot to add it in [wiki](https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare/wiki/Create-auto-renewal-SSL-certificate).

**Comment by trinib** [comment]
@mp68 I will redirect to here in wiki and forget the hassle.

**Comment by trinib** [comment]
> thanks👍. I already stated some of it in discussions [#14 (comment)](https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare/discussions/14#discussioncomment-2707819) but forgot to add it in [wiki](https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare/wiki/Create-auto-renewal-SSL-certificate).
> 
> ill add it

sorry about that did not read title properly 'only accessible via VPN'. I will add this enhancement
