### ISSUE TITLE
How is this different to nextdns?

### ISSUE THREAD

**Issue by anat0lius** [trinib/AdGuard-WireGuard-Unbound-Cloudflare#7]
Apart from self hosting

**Comment by trinib** [comment]
when you mean "this", you mean cloudflare compare to nextdns ? i use cloudflare cause of my location , you can use nextdns i guess with some few configurations

**Comment by anat0lius** [comment]
I mean to the whole solution. Nextdns also offers trackers blocking, encrypted queries and so on.

**Comment by trinib** [comment]
> I mean to the whole solution. Nextdns also offers trackers blocking, encrypted queries and so on.

ohh lol .. there is alot of different methods for these types of network security . i choose this setup cause of the devs and communities behind it.  you can go with your set up with nextdns if it works best for you .. if you want to know what is better as in security or speed , I HAVE NO IDEA .. someone will have to test that side by side lol. and sometimes things get updated and bug features so it is up to personal preference

**Comment by trinib** [comment]
@anat0lius hello you can use binds dig tool to check latency of your dns setup https://docs.digitalocean.com/products/networking/dns/resources/use-dig/#installing-dig

**Comment by oijkn** [comment]
@anat0lius With Nextdns you don't know what they do with yours data because the service is over the cloud.

With local solutions (Pi-hole, AdGuardHome, Unbound, Cloudflared, Stubby) your data are safe 😊
